RequestSystem.UI/Controllers/StatementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Domain.BaseEntity;
using Domain.Services;
using Domain.Statements;
using Domain.Statements.ValueObjects;
using Microsoft.AspNetCore.Mvc;
using StatementSystem.UI.Models;

namespace RequestSystem.UI.Controllers
{
    public class StatementController : Controller
    {
        [HttpGet]
        public async Task<IActionResult> Index(
            [FromServices] IStatementRepository repository,
            [FromQuery] FilterModel filter)
        {
            var statements = await repository.GetAll();

            var statementsModel = new List<StatementModel>();
            foreach(var statement in statements)
            {
                statementsModel.Add(new StatementModel(statement));
            }

            var filteredList = statementsModel
                .Where(filter.FilterExp)
                .ToList();

            var orderedList = GetOrderedList(filter.Order, filteredList);

            var model = new StatementIndexView()
            {
                Statements = orderedList,
                Filter = filter
            };

            return View(model);
        }

        #region Edit
        [HttpGet]
        public async Task<IActionResult> Edit(
            [FromServices] IStatementRepository repository,
            [FromRoute] Guid id)
        {
            var statement = await repository.GetStatement(new PrimaryKey(id)) as Statement;

            var model = new StatementModel(statement);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(
            [FromServices] IStatementService statementService,
            [FromForm] StatementModel input)
        {
            var statement = await statementService.ChangeStatementTitle(
                new PrimaryKey(input.StatementId),
                new StatementTitle(input.StatementTitle));

            var model = new StatementModel(statement);
            return View(model);
        }
        #endregion

        #region Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(
            [FromServices] IStatementService statementService,
            [FromForm] StatementModel input)
        {
            await statementService.CreateStatement(
                new StatementTitle(input.StatementTitle));
            return RedirectToAction("Index");
        }
        #endregion


        [HttpGet]
        public async Task<IActionResult> Delete(
            [FromServices] IStatementService statementService,
            [FromRoute] Guid id)
        {
            await statementService.DeleteStatement(new PrimaryKey(id));
            return RedirectToAction("Index");
        }

        private List<StatementModel> GetOrderedList(
            OrderState order, 
            List<StatementModel> statements)
        {
            switch(order)
            {
                case OrderState.CreateDateDesc: return statements.OrderByDescending(x => x.CreateDate).ToList();
                case OrderState.CreateDateAsc: return statements.OrderBy(x => x.CreateDate).ToList();
                case OrderState.StatusDesc: return statements.OrderByDescending(x => x.CurrentStatus.StatusCode).ToList();
                case OrderState.StatusAsc: return statements.OrderBy(x => x.CurrentStatus.StatusCode).ToList();
            }

            return statements;
        }
    }
}

RequestSystem.UI/Controllers/StatusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Domain.BaseEntity;
using Domain.Services;
using Domain.Statements;
using Domain.Statements.Status.ValueObjects;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using StatementSystem.UI.Models;

namespace StatementSystem.UI.Controllers
{
    public class StatusController : Controller
    {
        [HttpGet]
        public async Task<IActionResult> ChangeStatus(
            [FromServices] IStatementRepository statementRepository,
            [FromRoute] Guid id)
        {
            var statement = await statementRepository.GetStatement(new PrimaryKey(id));
            var currentStatusCode = (int)((Statement)statement).CurrentStatus.StatusCode;
            ViewBag.StatusItems = GetStatusItems(currentStatusCode);

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ChangeStatus(
            [FromServices] IStatementService statementService,
            [FromForm] StatusModel input)
        {
            await statementService.ChangeStatementStatus(
                new PrimaryKey(input.StatementId),
                (StatusCode)input.StatusCode,
                new StatusComment(input.Comment));

            return RedirectToAction("Edit", "Statement", new { id = input.StatementId });
        }

        private List<SelectListItem> GetStatusItems(int code) => code switch
        {
            0 => new List<SelectListItem>
            {
                new SelectListItem("Решена","1")
            },
            1 => new List<SelectListItem>
            {
                new SelectListItem("Возврат","2"),
                new SelectListItem("Закрыта","3")
            },
            2 => new List<SelectListItem>
            {
                new SelectListItem("Решена","1")
            },
            _ => new List<SelectListItem>()
        };
    }
}

RequestSystem.UI/Views/Statement/Create.cshtml
@model StatementModel
@{
    ViewData["Title"] = $"Новое заявление";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Новое заяление</h1>

<br />

@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <div class="form-group">
            <span>Наименование</span>
            <div class="col-md-10">
                @Html.TextBoxFor(x => x.StatementTitle, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-primary">Создать</button>
                @Html.ActionLink("Отмена", "Index", "Statement", null, new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
}

RequestSystem.UI/Views/Statement/Edit.cshtml
@model StatementModel
@{
    ViewData["Title"] = $"Заявление {Model.StatementId.ToString().Substring(0, 8)}";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.ActionLink("Назад", "Index", "Statement", null, new {@class="btn btn-primary" })

<br />
<br />

@using (Html.BeginForm("Edit", "Statement", FormMethod.Post))
{
    @Html.HiddenFor(s => s.StatementId)
    <table class="table table-bordered">
        <thead class="thead-dark">
            <tr>
                <td>Дата создания</td>
                <td>Дата изменения</td>
                <td>Наименование</td>
                <td>Состояние</td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Model.CreateDate</td>
                <td>@Model.EditDate</td>
                <td>@Html.TextBoxFor(x => x.StatementTitle, new { @class = "form-control-plaintext" })</td>
                <td>@await Component.InvokeAsync("StatusCodeSpan", new { statusCode = Model.CurrentStatus.StatusCode })</td>
            </tr>
        </tbody>
    </table>
    <button type="submit" class="btn btn-success">Сохранить</button>
    @Html.ActionLink("Удалить", "Delete", new { id = Model.StatementId }, new { @class = "btn btn-danger" })
    @if(Model.CurrentStatus.StatusCode != 3)
    {
        @Html.ActionLink("Изменить статус", "ChangeStatus", "Status", new { id = Model.StatementId }, new { @class = "btn btn-primary float-right" })
    }
}

<br />
<br />

<h3>История изменений статуса</h3>
<table class="table table-bordered">
    <thead class="thead-dark">
        <tr>
            <td>Дата создания</td>
            <td>Состояние</td>
            <td>Комментарий</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var status in Model.StatusHistory)
        {
            <tr>
                <td>@status.CreateDate</td>
                <td>@await Component.InvokeAsync("StatusCodeSpan", new { statusCode = status.StatusCode })</td>
                <td>@status.Comment</td>
            </tr>
        }
    </tbody>
</table>

RequestSystem.UI/Views/Statement/Index.cshtml
@model StatementIndexView
@{
    ViewData["Title"] = "Список заявлений";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />

<button class="btn btn-info" type="button" data-toggle="collapse" data-target="#filtration" aria-expanded="false" aria-controls="filtration">
    Фильтрация
</button>

<div class="collapse multi-collapse" id="filtration">
@using (Html.BeginForm("Index", "Statement", FormMethod.Get))
{
    <div class="form-row align-items-baseline">
        <div class="col-auto">
            <label>С</label>
            @Html.TextBoxFor(
            model => model.Filter.BeginDate,
            new { @type = "date", @class = "form-control" })
        </div>
        <div class="col-auto">
            <label>По</label>
            @Html.TextBoxFor(
            model => model.Filter.EndDate,
            new { @type = "date", @class = "form-control" })
        </div>
        <div class="col-auto">
            <label>Состояние</label>
            @Html.DropDownListFor(x => x.Filter.StatusCode,
            new SelectList(Model.Filter.StatusItems, "Value", "Text"),
            new { @class = "form-control" })
        </div>
        <div class="col-auto">
            <label>Сортировать по</label>
            @Html.DropDownListFor(x => x.Filter.Order,
            new SelectList(Model.Filter.OrderItems, "Value", "Text"),
            new { @class = "form-control" })
        </div>
        <div class="col-auto">
            <button type="submit" class="btn btn-primary">
                <i class="fas fa-sync"></i>
            </button>
        </div>
    </div>
}
</div>

<br />
<br />

@Html.ActionLink("Создать заявление", "Create", new { }, new { @class = "btn btn-primary" })
<br />
<br />

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Дата создания</th>
            <th>Дата изменения</th>
            <th>Наименование</th>
            <th>Статус</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var statement in Model.Statements)
        {
            <tr>
                <td>@statement.CreateDate</td>
                <td>@statement.EditDate</td>
                <td>@statement.StatementTitle</td>
                <td>@await Component.InvokeAsync("StatusCodeSpan", new { statusCode = statement.CurrentStatus.StatusCode })</td>
                <td>
                    @Html.ActionLink(
             "Подробнее",
             "Edit",
             new { id = statement.StatementId },
             new { @class = "btn btn-primary" })
                    @Html.ActionLink(
             "Удалить",
             "Delete",
             new { id = statement.StatementId },
             new { @class = "btn btn-danger" })
                </td>
            </tr>

        }
    </tbody>
</table>