RequestSystem.UI/Controllers/StatementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Domain.BaseEntity;
using Domain.Services;
using Domain.Statements;
using Domain.Statements.ValueObjects;
using Microsoft.AspNetCore.Mvc;
using StatementSystem.UI.Models;

namespace RequestSystem.UI.Controllers
{
    public class StatementController : Controller
    {
        [HttpGet]
        public async Task<IActionResult> Index(
            [FromServices] IStatementRepository repository,
            [FromQuery] FilterModel filter)
        {
            var statements = await repository.GetAll();

            var statementsModel = new List<StatementModel>();
            foreach(var statement in statements)
            {
                statementsModel.Add(new StatementModel(statement));
            }

            var filteredList = statementsModel
                .Where(filter.FilterExp)
                .ToList();

            var orderedList = GetOrderedList(filter.Order, filteredList);

            var model = new StatementIndexView()
            {
                Statements = orderedList,
                Filter = filter
            };

            return View(model);
        }

        #region Edit
        [HttpGet]
        public async Task<IActionResult> Edit(
            [FromServices] IStatementRepository repository,
            [FromRoute] Guid id)
        {
            var statement = await repository.GetStatement(new PrimaryKey(id)) as Statement;

            var model = new StatementModel(statement);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(
            [FromServices] IStatementService statementService,
            [FromForm] StatementModel input)
        {
            var statement = await statementService.ChangeStatementTitle(
                new PrimaryKey(input.StatementId),
                new StatementTitle(input.StatementTitle));

            var model = new StatementModel(statement);
            return View(model);
        }
        #endregion

        #region Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(
            [FromServices] IStatementService statementService,
            [FromForm] StatementModel input)
        {
            await statementService.CreateStatement(
                new StatementTitle(input.StatementTitle));
            return RedirectToAction("Index");
        }
        #endregion


        [HttpGet]
        public async Task<IActionResult> Delete(
            [FromServices] IStatementService statementService,
            [FromRoute] Guid id)
        {
            await statementService.DeleteStatement(new PrimaryKey(id));
            return RedirectToAction("Index");
        }

        private List<StatementModel> GetOrderedList(
            OrderState order, 
            List<StatementModel> statements)
        {
            switch(order)
            {
                case OrderState.CreateDateDesc: return statements.OrderByDescending(x => x.CreateDate).ToList();
                case OrderState.CreateDateAsc: return statements.OrderBy(x => x.CreateDate).ToList();
                case OrderState.StatusDesc: return statements.OrderByDescending(x => x.CurrentStatus.StatusCode).ToList();
                case OrderState.StatusAsc: return statements.OrderBy(x => x.CurrentStatus.StatusCode).ToList();
            }

            return statements;
        }
    }
}

RequestSystem.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Statement" asp-action="Index">Statement system</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>